### ISSUE TITLE
Support for 4.0.1

### ISSUE THREAD

**Issue by mlonn** [Ahryman40k/typescript-fhir-types#13]
When downloading json from https://www.hl7.org/fhir/observation.profile.json It does not validate with

`const structureDefinition: R4.IStructureDefinition = R4.RTTI_StructureDefinition.decode(jsons).value as R4.IStructureDefinition;`

since the current version is 4.0.1 and there are slight chagnes

**Comment by Ahryman40k** [comment]
Yes, you're right.
I actually working on it.

**Comment by mlonn** [comment]
Awesome thanks

**Comment by joejordan** [comment]
Hi, any update on 4.0.1 support? Thanks

**Comment by Ahryman40k** [comment]
Hi,

A lot of things happened on my side, meaning I'm not ready yet.
You can also push me a merge request if you know exactly what to do ?

Best,

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by mlonn** [comment]
I'm not working with FHIR any more.
