### ISSUE TITLE
Change to MIT Licence

### ISSUE THREAD

**Issue by Ahryman40k** [Ahryman40k/typescript-fhir-types#18]
Change to MIT licence.

**Comment by Kayes-Islam** [comment]
We are currently evaluating using this very useful library but GPL 3.0 license is problematic. It would be much appreciated if the license changed to MIT.

**Comment by Ahryman40k** [comment]
Hi Kayes, 
I open this issue because I'll change licence to MIT in a couple of day. 
Of course, it's a quick modification but I'm really busy. You can also prepare a Pull request if you want to help me. 
Best regards, 
Geoffrey

**Comment by Ahryman40k** [comment]
Licence has been updated since version 4.0.29.
Please update your dependency

**Comment by Kayes-Islam** [comment]
Thanks @Ahryman40k
