### ISSUE TITLE
Question: How did you generate all the interfaces?

### ISSUE THREAD

**Issue by dinbtechit** [Ahryman40k/typescript-fhir-types#28]
Great work!  Thanks

Just curious...

1) How up to date the interfaces are? 
2) How did generate the Typescript interfaces from the Fhir Json schema? For some reasons I couldn't generate them using json2ts.

**Comment by Ahryman40k** [comment]
Hi, 

Thanks, 
1. Interfaces are compliant with FHIR R4. All works on R5 road is ignored until it was released (By the end of the year)
2. No generator can help you that's the reason I created mine.
