### ISSUE TITLE
AuditEvent.recorded is not mandated

### ISSUE THREAD

**Issue by AllanHodkinson** [Ahryman40k/typescript-fhir-types#29]
Current AuditEvent interface `IAuditEvent` has

```
recorded?: string;
```

This field has a 1:1 cardinality in the FHIR spec (STU3/ DSTU4) so is mandatory.

**Comment by Ahryman40k** [comment]
You're right it's a mistake !

**Comment by Ahryman40k** [comment]
Fixed in 4.0.35
